name: quron_app

description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1


environment:
  sdk: ^3.8.1


dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  provider: ^6.1.5
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0
  easy_localization: ^3.0.7+1
  go_router: ^16.0.0
  flutter_animate: ^4.5.2
  google_sign_in:  ^6.1.5

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa/static/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa/static/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa/static/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa/static/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa/static/Comfortaa-SemiBold.ttf
          weight: 600

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/static/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/static/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/static/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/static/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito/static/Nunito-Italic.ttf
          style: italic

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true
  fonts:
    enabled: true
